apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: caas-apps-adherent1
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: mangue
            type: caas-webobject
            customValues: |
              image:
                repository: docker.depot.asso-cocktail.org/cocktail/application/mangue
              appName: "Mangue"
              cgiAdaptorUrl: "https://mangue.ckaas.asso-cocktail.com"

              resources:
                limits:
                  memory: "1Gi"
                requests:
                  memory: 784Mi

              service:
                type: ClusterIP

          
              ingress:
                enabled: true
                allowHttp: true
                className: "nginx"
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  kubernetes.io/tls-acme: "true"
                hosts:
                  - host: adherent1-mangue.ckaas.asso-cocktail.com
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls:
                  - secretName: adherent1-mangue.tls
                    hosts:
                      - adherent1-mangue.ckaas.asso-cocktail.com

              configFilesTree:
                - directory: "/config"
                  configFiles:
                    application-k8s.properties: |
                      APP_USE_CAS=NO
                      cocktail.feature.background.tasks=true
                      oracle.jdbc.timezoneAsRegion=false
                      DEFAULT_SESSION_TIME_OUT=10000
                      # Identifiant SAUT de l'application
                      # ManGUE base de production
                      APP_ID=MANGUE
                      # Connexion à SAUT =prioritaire sur GRHUM_PARAMETRES
                      SAUT_USER=YES
                      # URL de connexion a SAUT
                      SAUT_URL=https://apps.univ-lr.fr/cgi-bin/WebObjects/ServAut.woa/wa/
                      # SAUT_ID_TRANSLATION=ULOGIN:GRHUM,GRHUM:GRHUM,MANGUE:GRHUM
                      # Libelle long de l'identifiant de l'application
                      APP_ALIAS=ManGUE
                      # Libelle du Service utilise pour les impressions
                      SERVICE=Direction des Ressources Humaines
                      # Logs (cote Serveur)  detailles =O = oui, N = non
                      MODE_DEBUG=N
                      # Affichage (cote Serveur) des erreurs dans la console (O) ou dans un fichier (N)
                      MODE_CONSOLE=O
                      # Prise en compte d'un time zone par defaut
                      DEFAULT_TIME_ZONE=Europe/Paris
                      # Adresse mail de reception des messages (NE PAS MODIFIER)
                      APP_ADMIN_MAIL=mangue@cocktail.org
                      # Destinataires des logs d'erreur de l'application séparés par des virgules
                      MAIL_LOGS_ERREURS:
                      # Repertoire par defaut du directory d'impression sur le client
                      DIRECTORY_IMPRESSION_CLIENT=/tmp
                      # Path local - Chemin de generation des éditions
                      DIRECTORY_IMPRESSION=/cephfs/tmp
                      # Chemin des maquettes locales des editions contenues dans Mangue / Contents / Resources / Impressions
                      # Vous pouvez ne mettre dans ce repertoire que les éditions modifiees.
                      DIRECTORY_JASPER=/cephfs/reports/jasper/
                      # Chemin des maquettes locales des editions contenues dans Mangue / Contents / Resources / Mangue_Impressions
                      # Vous pouvez ne mettre dans ce repertoire que les éditions modifiees.
                      DIRECTORY_MODULE_IMPRESSION=/cephfs/reports/jasper/
                      # Mot de passe Administrateur
                      APP_ADMIN_PASSWORD=
                      #Clé donnant le chemin vers le fichier properties de configuration des logs
                      # Par defaut, les fichiers pris en compte sont ceux de Contents/Resources
                      #org.cocktail.application.client.log=/directory_to_change/log4jClient.properties
                      #org.cocktail.application.server.log=/directory_to_change/log4jServer.properties
                      spring.kafka.bootstrap-servers=gesprod-grh-kafka-cluster-kafka-bootstrap.gesprod.svc.cluster.local:9092
                      spring.kafka.reconnect.backoff.ms=20000
                      spring.kafka.max.block.ms=10000
                      # Activation/désactivation de la tache de traitement des évènements à envoyer à kafka
                      # A ne mettre en place que sur une seule instance si Mangue est sur du multi-instances
                      # pour cela, ajouter dans le WOMonitor au démarrage de l'instance -Dcocktail.feature.kafka.tasks=true
                      cocktail.feature.kafka.tasks=false
                      # Delai entre deux exécutions de la tache de traitement des évènements à envoyer à kafka
                      cocktail.mangue.kafka.delay.s=30
                      cocktail.mangue.kafka.schema-registry.url=http://gesprod-grh-kafka-stack-cp-schema-registry.gesprod.svc.cluster.local:8081
                      # Activation de la synchronisation de tous les dossiers de paye
                      # Si ce paramètre est à true, la gestion de la synchronisation générale se fera dans le menu "App / Paramètres"
                      cocktail.feature.synchroniserDossiersPayes=false
                      # url.grh-envoi-paye=http://grh-envoi-paye.etablissement.fr
                      # url.grh-envoi-paye=https://grh-envoi-paye-gesprod.calypso.univ-lr.fr
                      # QUESTION : comment est utilisée cette url (mangue.serveur --> evp.serveur ou mangue.client --> evp.serveur )
                      # k8s: <service-name>.<namespace>.svc.cluster.local:<service-port>
                      url.grh-envoi-paye=http://gesprod-grh-envoi-paye.gesprod.svc.cluster.local
                      # logs sql (DEBUG pour les avoirs)
                      log4j.logger.er.transaction.adaptor.EOAdaptorDebugEnabled=INFO
                      # # Nom du topic kafka agent
                      kafka.topic.boot-agent=GRH_AGENT
                      hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

          - name: grh-envoi-paye
            type: caas-springboot
            customValues: |
              image:
                repository: docker.depot.asso-cocktail.org/cocktail/application/grh-envoi-paye
              appName: "grh-envoi-paye"

              extraEnv:
                - name: "spring.profiles.active"
                  value: k8s
                - name: "spring.config.additional-location"
                  value: "/config/"
                - name: "spring.jmx.enabled"
                  value: "false"
                - name: "logging.config"
                  value: "/config/logback-k8s.xml"

              resources:
                limits:
                  memory: 1Gi
                requests:
                  memory: 256Mi

              oracle:
                host: bdorsref1.sb.asso-cocktail.org
                port: 5221
                user: grhum
                password: caasRHUM
                database: CAASUTF01

              ingress:
                enabled: true
                allowHttp: true
                className: "nginx"
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  kubernetes.io/tls-acme: "true"
                hosts:
                  - host: adherent1-grh-envoi-paye.ckaas.asso-cocktail.com
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls:
                  - secretName: adherent1-grh-envoi-paye.tls
                    hosts:
                      - adherent1-grh-envoi-paye.ckaas.asso-cocktail.com

              configFilesTree:
                - directory: "/config"
                  configFiles:
                    application-k8s.yaml: |
                      spring.main.banner-mode: OFF
                      management.endpoints.web.exposure.include: "*"
                      cas.server-login-url: "https://auth.asso-cocktail.fr/cas6/login"
                      cas.server-logout-url:  "https://auth.asso-cocktail.fr/cas6/logout"
                      cas.server: "https://auth.asso-cocktail.fr/cas6"
                      edition.actes-administratifs-templates.local-repository: /tmp
                      edition.nom-etablissement: Cocktail
                      edition.nom-service: "service:Marseille"
                      kafka:
                        enabled: false
                      logging:
                        pattern:
                          console: "%d{dd-MM-yyyy HH:mm:ss} %-5level [%-45.-45logger{45}] - %msg%n"
                        level:
                          org.hibernate.SQL: error
                          org.cocktail: info

                    logback-k8s.xml: |
                      <configuration debug="true">
                          <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                              <encoder>
                                  <pattern>%d{dd-MM-yyyy HH:mm:ss} %-5level [%-45.-45logger{45}] - %msg%n</pattern>
                              </encoder>
                          </appender>
                          <!-- LOG everything at INFO level -->
                          <root level="info">
                                  <appender-ref ref="STDOUT" />
                          </root>
                      </configuration>


  template:
    metadata:
      name: 'caas-adherent1-{{"{{"}}name{{"}}"}}'
      labels:
        caas.client.name: adherent1
        caas.app.type: '{{"{{"}}type{{"}}"}}'
        caas.app.name: '{{"{{"}}name{{"}}"}}'
    spec:
      project: caas-applications
      source:
        repoURL: 'git@forge.in.asso-cocktail.org:dsiadm/caas/caas-helm-charts.git'
        targetRevision: HEAD
        path: charts/{{"{{"}}type{{"}}"}}
        helm:
          parameters:
          - name: oracle.host
            value: bdorsref1.sb.asso-cocktail.org
          - name: oracle.port
            value: '5221'
          - name: oracle.user
            value: grhum
          - name: oracle.password
            value: caasRHUM
          - name: oracle.database
            value: CAASUTF01
          - name: "image.tag"
            value: "2022.1.13"
          values: |
            {{"{{"}}customValues{{"}}"}}
destination:
        namespace: adherent1-proto
        name: Dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true

